FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o bin/client client/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/client /app/client

# ENTRYPOINT [ "./client" ]