services:
  server1:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server1
    command: -port=8081 -forward=server2:8082 -id=1
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    ports:
      - 9091:8081
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.200.1

  server2:
    depends_on: 
      - server1
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server2
    command: -port=8082 -forward=server3:8083 -id=2
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    ports:
      - 9092:8082
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.200.2

  server3:
    depends_on: 
      - server1
      - server2
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server3
    command: -port=8083 -forward=server4:8084 -id=3
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    ports:
      - 9093:8083
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.200.3

  server4:
    depends_on: 
      - server1
      - server2
      - server3
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server4
    command: -port=8084 -forward=server5:8085 -id=4
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    ports:
      - 9094:8084
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.200.4

  server5:
    depends_on: 
      - server1
      - server2
      - server3
      - server4
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server5
    command: -port=8085 -id=5
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    ports:
      - 9095:8085
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.200.5
  
  client1:
    depends_on: 
      - server1
      - server2
      - server3
      - server4
      - server5
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: client1
    command: -destination=server1:8081 -id=1
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    networks:
      go_otel_test_network:
        ipv4_address: 192.168.100.1

networks:
  go_otel_test_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
