services:
  server1:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server1
    command: -port=8081 -next=server2:8082
    ports:
      - 8081:8081

  # server2:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.server
  #   container_name: server2
  #   command: -port=8082 -next=server2:8083
  #   ports:
  #     - 8082:8082

  # server3:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.server
  #   container_name: server3
  #   command: ./server -port=8083
  #   ports:
  #     - 8083:8083
  
  # client:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.client
  #   container_name: client
  #   command: -destination=server1:8081
  #   depends_on: 
  #     - server1
  #     - server2
  #     - server3