services:
  server1:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server1
    command: -port=8081 -forward=server2:8082
    ports:
      - 8081:8081

  server2:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server2
    command: -port=8082 -forward=server3:8083
    ports:
      - 8082:8082
    depends_on: 
      - server1

  server3:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server3
    command: -port=8083 -forward=server4:8084
    ports:
      - 8083:8083
    depends_on: 
      - server1
      - server2

  server4:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server4
    command: -port=8084
    ports:
      - 8084:8084
    depends_on: 
      - server1
      - server2
      - server3
  
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    command: -destination=server1:8081
    depends_on: 
      - server1
      - server2
      - server3
      - server4

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411